name: computational_redistictring
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - contourpy=1.2.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.2
  - fontconfig=2.14.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - geos=3.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.8
  - libedit=3.1.20230828
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libpng=1.6.39
  - libpq=12.17
  - libsqlite=3.45.2
  - libstdcxx-ng=13.2.0
  - libtiff=4.4.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - munkres=1.1.4
  - mysql=5.7.24
  - ncurses=6.4.20240210
  - numpy=1.26.4
  - openjpeg=2.4.0
  - openssl=3.2.1
  - packaging=23.2
  - pcre2=10.42
  - pillow=10.2.0
  - pip=24.0
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.2
  - python-dateutil=2.8.2
  - python_abi=3.12
  - qt-main=5.15.2
  - readline=8.2
  - setuptools=69.2.0
  - shapely=2.0.3
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.13
  - tornado=6.3.3
  - tzdata=2024a
  - wheel=0.43.0
  - xkeyboard-config=2.41
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
